name: Feature request
description: Make a feature request for the collection
labels: ["enhancement"]
assignees:
  - willpinha
body:
  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature you are requesting
    validations:
      required: true

  - type: textarea 
    attributes:
      label: Benefits
      description: Highlight the advantages and benefits of implementing this feature

  - type: textarea
    attributes:
      label: Implementation suggestions
      description: If you have any suggestions or ideas on how the feature could be implemented, share them here. This is optional, and developers may have their own approach
  