name: 🏷️ New tag
description: Propose a new tag
labels: ["enhancement"]
assignees: "willpinha"
body:
- type: input
  attributes:
    label: "Tag name"
    description: "It must be in lower camel case, singular, and cannot already exist"
    placeholder: "Example: landingPage"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Use cases"
    description: "Give a description of use cases for this tag"
    placeholder: "Example: This tag can be associated with any section of a landing page, such as hero sections, FAQ sections, clients sections and pricing sections"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Screenshots"
    description: "Add screenshots demonstrating UI examples for the tag"
