name: 🎨 New UI example 
description: Propose a new UI example for an existing tag
labels: ["enhancement"]
assignees: "willpinha"
body:
- type: input
  attributes:
    label: "For which tag?"
    description: "The tag name must already exist"
    placeholder: "Example: navbar"
  validations:
    required: true
- type: input
  attributes:
    label: "UI example name"
    description: "It must be in lower camel case, singular, and cannot already exist in the tag"
    placeholder: "Example: simpleWithDropdown"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Description"
    description: "Give a description of how the UI example would look like"
    placeholder: "Example: A navbar with logo on the left side, menu items on the right side. One of the items is a dropdown"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Screenshots"
    description: "Add screenshots demonstrating desktop and mobile versions of the UI example"
- type: dropdown
  attributes:
    label: "Do you want to implement the UI example?"
    description: "If you want to, please take a look at the [CONTRIBUTING.md](https://github.com/willpinha/daisy-collection/blob/master/CONTRIBUTING.md) file"
    options:
      - Yes, I do want to implement it!
      - No, I'm just giving the idea
    default: 1
  validations:
    required: true
