name: Report for the SvelteKit project
description: Create a report for bugs in the SvelteKit project
labels: ["bug"]
assignees: "willpinha"
body:
- type: textarea
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: markdown
  attributes:
    label: What are the steps to reproduce this issue?
    description: Give a list of steps to reproduce the issue
    value: |
      1. Click on "..."
      2. Scroll down to "..."
      3. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Any logs, error output, etc?
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks
    render: shell
