name: ⚠️ Report a problem 
description: Report a problem in a UI example
labels: ["problem"]
assignees:
  - willpinha
body:
  - type: input
    attributes:
      label: For which tag?
      description: Write the name of the tag where the UI example is located
    validations:
      required: true
    
  - type: input
    attributes:
      label: For which UI example?
      description: Write the name of the UI example with problems 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and concise description of the problem you are encountering
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots (if applicable)
      description: Include screenshots that help illustrate the problem

  - type: dropdown 
    attributes:
      label: Do you want to contribute to this issue?
      description: >
        If you want, you will be assigned to the issue and can make a pull request fixing it.
        Otherwise, a `help-wanted` label will be added to it. The first contributor who asks to
        contribute will be assigned to the issue and the `help-wanted` label will be removed
      options:
        - Yes, I want to contribute!
        - No, I will leave the issue to another contributor
      default: 0
    validations:
      required: true
