name: Report for an UI example 
description: Create a report for issues with an existing UI example
labels: ["bug"]
assignees: "willpinha"
body:
- type: input
  attributes:
    label: Which tag?
    description: The tag name must already exist
    placeholder: "Example: navbar"
  validations:
    required: true
- type: input
  attributes:
    label: Which UI example?
    description: The UI example must already exist
    placeholder: "Example: simpleWithDropdown"
  validations:
    required: true
- type: textarea
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  attributes:
    label: What are the steps to reproduce this issue?
    description: Give a list of steps to reproduce the issue
    value: |
      1. Click on "..."
      2. Scroll down to "..."
      3. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem
